apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-dev
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
    project: default
  source: 
    path: helm-chart
    repoURL: https://github.com/momoelabdi/windCatchers.git
    targetRevision: main
    helm:
      valueFiles:
        - envs/dev/helm/values-dev.yaml
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true