apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-dev
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm-chart
    repoURL: https://github.com/momoelabdi/windCatchers.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../helm/values-dev.yml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
