apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-dev
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm-chart
    repoURL: https://github.com/momoelabdi/windCatchers.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - helm/values-dev.yaml
      # ignoreMissingValueFiles: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
